# -*- coding: utf-8 -*-
"""
IDA Pro 9 Script: Regenerate TSM_Offsets.h from Signature Scans (ARM64 Version)
This script uses the signatures generated by ida_generate_signatures.py to find
offsets in a new version of the ARM64 binary and regenerate the header file.
"""

import ida_bytes
import ida_segment
import idaapi
import idautils
import idc
import json
import os
from collections import OrderedDict

def get_image_base():
    """Get the image base address"""
    return idaapi.get_imagebase()

def pattern_to_bytes(pattern_str):
    """
    Convert pattern string (e.g., "48 89 5C 24 ?? 48 89 74") to bytes and mask
    
    Returns:
        tuple: (bytes, mask_bytes) where mask_bytes uses 0xFF for match, 0x00 for wildcard
    """
    parts = pattern_str.split()
    pattern_bytes = []
    mask_bytes = []
    
    for part in parts:
        if part == "??":
            pattern_bytes.append(0)
            mask_bytes.append(0x00)  # Wildcard
        else:
            pattern_bytes.append(int(part, 16))
            mask_bytes.append(0xFF)  # Must match
    
    return bytes(pattern_bytes), bytes(mask_bytes)

def find_pattern(pattern_str, start_ea=None, end_ea=None):
    """
    Search for a pattern in the binary
    
    Args:
        pattern_str: Pattern string (e.g., "48 89 5C 24 ?? 48")
        start_ea: Start address (None = start of segment)
        end_ea: End address (None = end of segment)
    
    Returns:
        list: List of addresses where pattern was found
    """
    if start_ea is None:
        start_ea = ida_segment.get_first_seg().start_ea
    if end_ea is None:
        end_ea = ida_segment.get_last_seg().end_ea
    
    results = []
    current_ea = start_ea
    
    # Use find_bytes which is a higher-level wrapper
    while current_ea < end_ea:
        found_ea = ida_bytes.find_bytes(
            pattern_str,
            current_ea,
            end_ea,
            16,  # radix (hex)
            ida_bytes.BIN_SEARCH_FORWARD | ida_bytes.BIN_SEARCH_NOSHOW
        )
        
        if found_ea == idaapi.BADADDR:
            break
        
        results.append(found_ea)
        current_ea = found_ea + 1
    
    return results

def scan_signature(sig_data):
    """
    Scan for a signature and return the offset
    
    Args:
        sig_data: Signature data dictionary
    
    Returns:
        int or None: Found offset (RVA) or None if not found
    """
    pattern = sig_data["pattern"]
    sig_type = sig_data["type"]
    pattern_offset = sig_data.get("pattern_offset", 0)
    
    # Search for pattern
    matches = find_pattern(pattern)
    
    # If no matches, try alternative pattern if available
    if not matches and "alt_pattern" in sig_data:
        print(f"    Trying alternative pattern...")
        matches = find_pattern(sig_data["alt_pattern"])
        if matches:
            pattern_offset = sig_data.get("alt_offset", 0)
    
    if not matches:
        return None
    
    if len(matches) > 1:
        print(f"    [!] Warning: Multiple matches found ({len(matches)}), using first")
    
    # Calculate the actual offset based on pattern_offset and type
    found_ea = matches[0]
    
    # Handle different signature types
    if sig_type == "data_xref":
        # For data xrefs, extract the data address from the instruction
        xref_insn_ea = found_ea + pattern_offset
        insn = idautils.DecodeInstruction(xref_insn_ea)
        if insn:
            # Look for memory operand (the data reference)
            data_found = False
            for op in insn.ops:
                if op.type == idaapi.o_mem:
                    # This is the data address
                    found_ea = op.addr
                    print(f"    Extracted data address: 0x{found_ea:X}")
                    data_found = True
                    break
            
            if not data_found:
                # Couldn't extract data address - return xref location with marker
                print(f"    [!] Could not extract data address from instruction")
                print(f"    [!] Returning xref instruction location: 0x{xref_insn_ea:X}")
                print(f"    [!] Manual resolution needed - check instruction at this address")
                # Return special marker value that we'll handle in write_header
                return ("XREF", xref_insn_ea - image_base)
        else:
            print(f"    [!] Warning: Could not decode instruction for data_xref")
            return None
    else:
        # Regular pattern - apply pattern_offset
        found_ea = found_ea + pattern_offset
    
    # Convert back to RVA (offset from image base)
    image_base = get_image_base()
    rva = found_ea - image_base
    
    return rva

def load_signatures(input_file):
    """Load signatures from JSON file"""
    if not os.path.exists(input_file):
        print(f"[!] Error: Signatures file not found: {input_file}")
        print("Please run ida_generate_signatures.py first!")
        return None
    
    with open(input_file, 'r') as f:
        return json.load(f)

def scan_all_signatures(signatures):
    """Scan all signatures and return updated offsets"""
    print(f"Scanning {len(signatures)} signatures...\n")
    
    found_offsets = OrderedDict()
    failed = []
    
    # First, populate with all original offsets from signatures
    for name, sig_data in signatures.items():
        found_offsets[name] = sig_data['offset']
    
    for name, sig_data in signatures.items():
        print(f"Scanning {name}...")
        print(f"  Original offset: 0x{sig_data['offset']:X}")
        
        try:
            new_offset = scan_signature(sig_data)
            
            if new_offset is not None:
                # Check if it's a special XREF marker tuple
                if isinstance(new_offset, tuple) and new_offset[0] == "XREF":
                    found_offsets[name] = new_offset
                    print(f"  ⚠ Found xref instruction at: 0x{new_offset[1]:X} (manual resolution needed)")
                else:
                    found_offsets[name] = new_offset
                    
                    if new_offset == sig_data['offset']:
                        print(f"  ✓ Found at: 0x{new_offset:X} (unchanged)")
                    else:
                        print(f"  ✓ Found at: 0x{new_offset:X} (moved from 0x{sig_data['offset']:X})")
            else:
                print(f"  [!] Not found!")
                failed.append(name)
                # Keep old offset as fallback (already set above)
                
        except Exception as e:
            print(f"  [!] Error: {e}")
            failed.append(name)
            # Keep old offset as fallback (already set above)
    
    print(f"\n{'='*80}")
    print(f"Found: {len(found_offsets) - len(failed)}/{len(signatures)}")
    if failed:
        print(f"Failed: {len(failed)} signatures")
        print(f"Failed offsets: {', '.join(failed)}")
    
    return found_offsets, failed

def generate_header(offsets, failed_offsets, output_file="offsets_new.h"):
    """Generate the C++ header file in ARM64 format - matches exact structure of offsets.h"""
    
    # Order exactly as in the original offsets.h file
    ordered_offsets = [
        ("Core game offsets", [
            "Game", "AudienceBarn"
        ]),
        ("Structure/layout offsets", [
            ("kLuaState", 0x20, "lua_State* at [Game + 0x20]"),
            ("kAvatarBarn", 0x310, "avatarBarn* at [Game + 0x310]"),
            ("kAccountBarn", 0x8, "accountBarn* at [AudienceBarn + 0x8]"),
            ("kAvatarOutfit", 0x58, "outfit* at [kAvatarBarn + kAvatarLocalSlot + kAvatarSlotStride*index + 0x58]"),
            ("kAvatarLocalSlot", 0x30, "LocalAvatar* at [kAvatarBarn + kAvatarLocalSlot + kAvatarSlotStride * index]"),
            ("kAvatarSlotStride", 0xEC30, "distance between avatar slots in the barn"),
            ("kAvatarPosition", 0x18, "position vec* pointer field at [kAvatarBarn + kAvatarLocalSlot + kAvatarSlotStride*index + 0x18]"),
            ("kAvatarShout", 0x60, "shout field at [Avatar + 0x60]"),
            ("kLevelName", 0x8E8, "char* at [Game + 0x8E8]"),
            ("kLoadingType", 0x1398, "byte* at [kAccountBarn + 0x1398]"),
            ("kGameSpeedBarn", 0x30, "GameSpeed* at [kAudienceBarn + kGameSpeedBarn]"),
            ("kGameSpeedDelta", 0x28, "float at [kGameSpeedBarn + kGameSpeedDelta]"),
            ("kCameraIntermediate", 0x150, "ptr* at [CameraSystem + 0x150]"),
            ("kViewProjectionMatrix", 0x230, "ViewProjectionMatrix* at [[CameraSystem + kCameraIntermediate] + kViewProjectionMatrix]"),
        ]),
        ("Avatar outfit offsets", [
            ("kHeight", 0x181C, "float at [outfit + 0x181C]"),
            ("kScale", 0x1820, "float at [outfit + 0x1820]"),
            ("kVoice", 0x1990, "uint8_t at [outfit + 0x1990]"),
            ("kStance", 0x1991, "uint8_t at [outfit + 0x1991]"),
            ("kHair", 0x594, "const char* at [outfit + 0x594]"),
            ("kMask", 0x7C4, "const char* at [outfit + 0x7C4]"),
            ("kNeck", 0x9F4, "const char* at [outfit + 0x9F4]"),
            ("kBody", 0x134, "const char* at [outfit + 0x134]"),
            ("kFeet", 0xC24, "const char* at [outfit + 0xC24]"),
            ("kWing", 0x364, "const char* at [outfit + 0x364]"),
            ("kProp", 0x12B4, "const char* at [outfit + 0x12B4]"),
        ]),
        ("Function offsets", [
            "kLuaDebugDoString", "kLuaPushLightUserData", "kWingBuffUpdate",
            "kRadianceBarn", "kAccountServerSetSession", "kHttpClientSetUserAgent",
            "kShouldDisplay", "kCameraSystemInitialize"
        ]),
        ("Patch offsets", [
            "kInvincibility", "kAutoCharge", "kDisableRainDrain", "kDarkCreatureTame",
            "kAllowAfk", "kRunSpeed", "kSuperSlidey", "kAutoCollectAllFragments",
            "kAutoFragmentWarp", "kFastBurn", "kDyeDebug", "kEnableAllRelationshipAbilities",
            "kFakeCapeLevelEnabled", "kFakeCapeLevel", "kAllowOverride", "kSunMoonXPosition",
            "kSunMoonYPosition", "kSunMoon", "kSunMoonSize", "kMoonPhase", "kExposure",
            "kFlameToCandleScale", "kFlowerHeight", "kFlowerSize", "kEnableGameCamSnap",
            "kAvatarCharcoaling", "kForceEthereal", "kAllNpcsHaveRadar", "kRevealPlayers",
            "kEnableMultiplayer", "kDisableGates", "kFastHome", "kFreezeKrills",
            "kBirthdayKrills", "kHideHudExceptForStarFragments", "kTguiPauseAnimation",
            "kUiShowHierarchy", "kDebugShowSpiritLocations", "kShowRadarForPreviousWingBuffs",
            "kEnableShrineRadar", "kShowAllFeedback", "kDebugLevelLinks", "kFishSchoolDebug",
            "kTvDebugUi", "kDisableWindWall", "kDisableLevelChangeEvents", "kDisableTerrain",
            "kDisableObjects", "kDisableObjectSkirts", "kDisableModels", "kDisableAvatars",
            "kEnableGravity", "kEnableClouds", "kEnableWater", "kEnableOcean",
            "kDisableLights", "kAutoCompleteQuests", "kAutoBurnDyes", "kAutoBurnDyes1",
            "kSuperLaunch", "kSpellEmitter", "kScooterMode", "kRainbowGlow",
            "kRainbowTrails", "kBubbleTrails", "kUnlockTrust",
        ]),
    ]
    
    lines = []
    lines.append("#pragma once\n")
    lines.append("\n")
    lines.append("#include <cstdint>\n")
    lines.append("\n")
    lines.append("namespace tsm { namespace game { namespace Offsets {\n")
    lines.append("\n")
    
    for category_name, offset_list in ordered_offsets:
        lines.append(f"\t// {category_name}\n")
        
        for item in offset_list:
            # Check if it's a hardcoded offset (tuple with name, value, comment)
            if isinstance(item, tuple):
                name, offset_val, comment_text = item
                lines.append(f"\tconstexpr std::uintptr_t {name} = 0x{offset_val:X}; // {comment_text}\n")
            else:
                # It's a scanned offset name (string)
                name = item
                
                # Get value from scanned offsets
                if name in offsets:
                    offset_val = offsets[name]
                else:
                    # Offset wasn't in signatures JSON at all (generation failed)
                    # Mark it as needing manual update and skip
                    lines.append(f"\t// constexpr std::uintptr_t {name} = 0x0; // [!] SIGNATURE GENERATION FAILED - NEEDS MANUAL UPDATE\n")
                    continue
                
                # Add comment if failed or special case
                comment = ""
                if name in failed_offsets:
                    comment = " // [!] SIGNATURE NOT FOUND - NEEDS MANUAL UPDATE"
                elif isinstance(offset_val, tuple) and offset_val[0] == "XREF":
                    # Special case: couldn't extract data address, showing xref location
                    xref_offset = offset_val[1]
                    comment = f" // [!] XREF ONLY - Manual resolution needed at 0x{xref_offset:X}"
                    offset_val = xref_offset
                
                lines.append(f"\tconstexpr std::uintptr_t {name} = 0x{offset_val:X};{comment}\n")
        
        lines.append("\n")
    
    # Add the plant burn offsets at the end (with comments from original header)
    plant_offsets = [
        ("kAutoBurnPlant1", "LDR S0, [X10,#0x248]"),
        ("kAutoBurnPlant2", "LDR S0, [X10,#0x248]"),
        ("kAutoBurnPlant3", "LDR S0, [X9,#0x248]"),
    ]
    for name, insn_comment in plant_offsets:
        if name in offsets:
            offset_val = offsets[name]
            comment = f" // {insn_comment}"
            if name in failed_offsets:
                comment += " [!] SIGNATURE NOT FOUND - NEEDS MANUAL UPDATE"
            lines.append(f"\tconstexpr std::uintptr_t {name} = 0x{offset_val:X};{comment}\n")
    lines.append("\n")
    
    lines.append("} } } // namespace tsm::game::Offsets\n")
    
    # Save to file next to IDB
    import os
    idb_dir = os.path.dirname(idc.get_idb_path())
    output_path = os.path.join(idb_dir, output_file)
    
    with open(output_path, 'w') as f:
        f.writelines(lines)
    
    print(f"\n✓ Header file saved to: {output_path}")
    
    if failed_offsets:
        print(f"\n[!] WARNING: {len(failed_offsets)} offsets need manual update!")
        print("Search for '[!] SIGNATURE NOT FOUND' comments in the generated file.")
    
    return output_path

def main():
    print("="*80)
    print("TSM Offset Regenerator for IDA Pro 9 (ARM64)")
    print("="*80)
    print()
    
    # Get signatures file path
    idb_path = idc.get_idb_path()
    default_sig_file = idb_path.replace(".i64", "_signatures.json").replace(".idb", "_signatures.json")
    
    # Try to load signatures
    sig_file = default_sig_file
    if not os.path.exists(sig_file):
        # Prompt user for file
        sig_file = idaapi.ask_file(0, "*.json", "Select signatures JSON file")
        if not sig_file:
            print("[!] No signatures file selected, aborting.")
            return
    
    print(f"Loading signatures from: {sig_file}\n")
    signatures = load_signatures(sig_file)
    
    if not signatures:
        return
    
    # Scan all signatures
    found_offsets, failed = scan_all_signatures(signatures)
    
    # Generate header file
    output_file = generate_header(found_offsets, failed)
    
    print("\n" + "="*80)
    print("DONE! Review the generated header file and update any failed offsets manually.")
    print("="*80)

if __name__ == "__main__":
    main()
